export type GalleryImage = {
  id: string;
  title: string;
  description: string;
  src: string;
};

export const galleryImages: GalleryImage[] = [
  
  {
    id: "gemini-c82r93",
    title: "Gemini c82r93",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105883/Gemini_Generated_Image_c82r93c82r93c82r_vgw0dq.png",
  },
  {
    id: "gemini-asfcm9",
    title: "Gemini asfcm9",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105884/Gemini_Generated_Image_asfcm9asfcm9asfc_zkkuts.png",
  },
  {
    id: "gemini-9y49y3",
    title: "Gemini 9y49y3",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105883/Gemini_Generated_Image_9y49y39y49y39y49_kcslnm.png",
  },
  {
    id: "gemini-fmrofp",
    title: "Gemini fmrofp",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105884/Gemini_Generated_Image_fmrofpfmrofpfmro_xjgnll.png",
  },
  {
    id: "gemini-fnjkz6",
    title: "Gemini fnjkz6",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105885/Gemini_Generated_Image_fnjkz6fnjkz6fnjk_qu5tnk.png",
  },
  {
    id: "gemini-jdd5jy",
    title: "Gemini jdd5jy",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105885/Gemini_Generated_Image_jdd5jyjdd5jyjdd5_ibhhyi.png",
  },
  {
    id: "gemini-huoxvr",
    title: "Gemini huoxvr",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105885/Gemini_Generated_Image_huoxvrhuoxvrhuox_c8gpog.png",
  },
  {
    id: "gemini-vn3yig",
    title: "Gemini vn3yig",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105885/Gemini_Generated_Image_vn3yigvn3yigvn3y_cwjgxo.png",
  },
  {
    id: "gemini-vhtq7j",
    title: "Gemini vhtq7j",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105885/Gemini_Generated_Image_vhtq7jvhtq7jvhtq_xzjfsi.png",
  },
  {
    id: "gemini-v8yia",
    title: "Gemini v8yia",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105885/Gemini_Generated_Image_v8yiav8yiav8yiav_uwc2g2.png",
  },
  {
    id: "gemini-yl3p02",
    title: "Gemini yl3p02",
    description: "Generated image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105886/Gemini_Generated_Image_yl3p02yl3p02yl3p_gpvf8g.png",
  },
  {
    id: "moisturiser-kdyz8b",
    title: "Moisturiser",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105886/Moisturiser_kdyz8b.png",
  },
  {
    id: "moisturiser-glorious",
    title: "Moisturiser Glorious",
    description: "Brand packaging",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105886/Moisturiser_Glorious_y1qlwb.png",
  },
  {
    id: "moisturiser-glorious-04",
    title: "Moisturiser Glorious 04",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105887/Moisturiser_Glorious_04_jfjttc.png",
  },
  {
    id: "moisturiser-glorious-02",
    title: "Moisturiser Glorious 02",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105887/Moisturiser_Glorious_02_lkx3nf.png",
  },
  {
    id: "moisturiser-glorious-03",
    title: "Moisturiser Glorious 03",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105887/Moisturiser_Glorious_03_n3sevg.png",
  },
  {
    id: "moisturiser-glorious-05",
    title: "Moisturiser Glorious 05",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105887/Moisturiser_Glorious_05_qbyzzb.png",
  },
  {
    id: "moisturiser-glorious-01",
    title: "Moisturiser Glorious 01",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105887/Moisturiser_Glorious_01_sxublf.png",
  },
  {
    id: "moisturiser-glorious-06",
    title: "Moisturiser Glorious 06",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105888/Moisturiser_Glorious_06_ul9lzf.png",
  },
  {
    id: "moisturiser-glorious-07",
    title: "Moisturiser Glorious 07",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105888/Moisturiser_Glorious_07_kxl2l8.png",
  },
  {
    id: "moisturiser-glorious-09",
    title: "Moisturiser Glorious 09",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105888/Moisturiser_Glorious_09_je3wtg.png",
  },
  {
    id: "moisturiser-glorious-08",
    title: "Moisturiser Glorious 08",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105888/Moisturiser_Glorious_08_wcuait.png",
  },
  {
    id: "moisturiser-glorious-11",
    title: "Moisturiser Glorious 11",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105889/Moisturiser_Glorious_11_i0rur8.png",
  },
  {
    id: "moisturiser-glorious-10",
    title: "Moisturiser Glorious 10",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105889/Moisturiser_Glorious_10_xjpnwt.png",
  },
  {
    id: "moisturiser-glorious-14",
    title: "Moisturiser Glorious 14",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105889/Moisturiser_Glorious_14_zcofgk.png",
  },
  {
    id: "moisturiser-glorious-13",
    title: "Moisturiser Glorious 13",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105889/Moisturiser_Glorious_13_ruyzlj.png",
  },
  {
    id: "moisturiser-glorious-12",
    title: "Moisturiser Glorious 12",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105889/Moisturiser_Glorious_12_i19tfb.png",
  },
  {
    id: "moisturiser-glorious-15",
    title: "Moisturiser Glorious 15",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105889/Moisturiser_Glorious_15_ddbsmu.png",
  },
  {
    id: "moisturiser-glorious-16",
    title: "Moisturiser Glorious 16",
    description: "Packaging image",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105890/Moisturiser_Glorious_16_tplezf.png",
  },
  {
    id: "glass-serum",
    title: "Glass Serum",
    description: "Premium beauty essentials styled for editorial photography.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.30_hmsagi",
  },
  {
    id: "spa-light",
    title: "Spa Light",
    description: "Minimal wellness setup with lush greenery and calm tones.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.22_unxims",
  },
  {
    id: "mirror-luxe",
    title: "Mirror Luxe",
    description: "Luxury beauty details captured in an elegant studio vignette.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.22_1_t9j4va",
  },
  {
    id: "rose-petal",
    title: "Rose Petal",
    description: "Soft focus floral accents with premium skincare packaging.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.22_2_yhuzpw",
  },
  {
    id: "cream-texture",
    title: "Cream Texture",
    description: "Close-up product texture shot with gentle color contrast.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.23_zqbhuk",
  },
  {
    id: "pearl-detail",
    title: "Pearl Detail",
    description: "Soft white lighting highlights elegant beauty accessories.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.23_2_ooh1mv",
  },
  {
    id: "evening-glow",
    title: "Evening Glow",
    description: "Moody editorial shot that feels modern and premium.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.24_mm233o",
  },{
    id: "new-one",
    title: "Conditioner Detail",
    description: "Soft white lighting highlights elegant beauty accessories.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.26_2_carg4m",
  },
  {
    id: "new-three",
    title: "Evening Glow",
    description: "Moody editorial shot that feels modern and premium.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.27_2_ek4pgo",
  },{
    id: "new-two",
    title: "Pearl Detail",
    description: "Soft white lighting highlights elegant beauty accessories.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.30_xalhgt",
  },
  {
    id: "new-four",
    title: "Evening Glow",
    description: "Moody editorial shot that feels modern and premium.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/WhatsApp_Image_2026-06-09_at_08.46.30_1_caftag",
  },
  {
    id: "new-six",
    title: "Evening Glow",
    description: "Moody editorial shot that feels modern and premium.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781105883/Gemini_Generated_Image_b8gw1wb8gw1wb8gw_rtv1dv.png",
  },
  {
    id: "radiant-skin-01",
    title: "Radiant Confidence",
    description: "Clean beauty portrait highlighting natural glow and healthy skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106615/Gemini_Generated_Image_fgz1rcfgz1rcfgz1_sutenb.png",
  },
  {
    id: "radiant-skin-02",
    title: "Pure Elegance",
    description: "Premium skincare visual with a modern editorial aesthetic.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106615/Gemini_Generated_Image_fpor8qfpor8qfpor_ukfqkg.png",
  },
  {
    id: "radiant-skin-03",
    title: "Natural Beauty",
    description: "Fresh and vibrant look designed to showcase healthy skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106614/Gemini_Generated_Image_dbpbpidbpbpidbpb_eqdpgv.png",
  },
  {
    id: "radiant-skin-04",
    title: "Golden Aura",
    description: "Luxury-inspired beauty shot with warm lighting and depth.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106614/Gemini_Generated_Image_ccjqfkccjqfkccjq_tgjl51.png",
  },
  {
    id: "radiant-skin-05",
    title: "Fresh Essence",
    description: "Bright skincare imagery focused on clarity and freshness.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106614/Gemini_Generated_Image_7maaq27maaq27maa_yfaqlq.png",
  },
  {
    id: "product-showcase-01",
    title: "Glorious Face Wash",
    description: "Premium product presentation crafted for a luxury skincare brand.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106614/face_Wash_Glorious_06_eqzpi3.png",
  },
  {
    id: "product-showcase-02",
    title: "Daily Refresh",
    description: "Minimal product display emphasizing purity and effectiveness.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106614/face_Wash_Glorious_05_di1r8a.png",
  },
  {
    id: "product-showcase-03",
    title: "Luxury Care",
    description: "Elegant product shot designed for premium brand storytelling.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106614/face_Wash_Glorious_04_s71ic0.png",
  },
  {
    id: "product-showcase-04",
    title: "Pure Hydration",
    description: "Clean and modern composition highlighting skincare benefits.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106613/face_Wash_Glorious_02_rt0jjf.png",
  },
  {
    id: "product-showcase-05",
    title: "Signature Formula",
    description: "Hero product visual created for impactful brand promotion.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106613/face_Wash_Glorious_01_mauvlo.png",
  },
  {
    id: "beauty-editorial-01",
    title: "Modern Grace",
    description: "Fashion-inspired portrait blending elegance with confidence.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106612/Gemini_Generated_Image_wyy3xlwyy3xlwyy3_bgvl85.png",
  },
  {
    id: "beauty-editorial-02",
    title: "Timeless Glow",
    description: "Contemporary beauty image with premium visual appeal.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106612/Gemini_Generated_Image_xdhdjgxdhdjgxdhd_r4xdnm.png",
  },
  {
    id: "beauty-editorial-03",
    title: "Authentic Beauty",
    description: "Natural portrait capturing confidence and individuality.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106612/unnamed_g5j4nz.jpg",
  },
  {
    id: "beauty-editorial-04",
    title: "Soft Radiance",
    description: "Editorial-style visual with refined beauty aesthetics.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106609/Gemini_Generated_Image_nm7fo9nm7fo9nm7f_fog1mz.png",
  },
  {
    id: "beauty-editorial-05",
    title: "Elegant Presence",
    description: "Premium portrait crafted to evoke sophistication and charm.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106609/Gemini_Generated_Image_r6dbjrr6dbjrr6db_plkqlu.png",
  },
  {
    id: "beauty-editorial-06",
    title: "Fresh Perspective",
    description: "Creative visual celebrating confidence and skincare excellence.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106609/Gemini_Generated_Image_oeonjjoeonjjoeon_mosxp1.png",
  },
  {
    id: "beauty-editorial-07",
    title: "Luminous Touch",
    description: "High-end beauty artwork featuring soft premium lighting.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106609/Gemini_Generated_Image_o9y8o8o9y8o8o9y8_tfg7am.png",
  },
  {
    id: "beauty-editorial-08",
    title: "Glow Redefined",
    description: "Luxury skincare campaign visual designed for modern brands.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106609/Gemini_Generated_Image_ftxks7ftxks7ftxk_fi0ht1.png",
  },
   {
    id: "haircare-01",
    title: "Silky Perfection",
    description: "Premium haircare campaign highlighting smooth, healthy, and vibrant hair.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106926/Gemini_Generated_Image_n0z9ebn0z9ebn0z9_ujfuis.png",
  },
  {
    id: "haircare-02",
    title: "Shampoo & Conditioner Duo",
    description: "Professional product showcase featuring a complete haircare solution.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106926/Shampoo_Conditioner_tbky3w.png",
  },
  {
    id: "haircare-03",
    title: "Healthy Hair Glow",
    description: "Elegant beauty visual emphasizing nourishment, shine, and confidence.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106926/Gemini_Generated_Image_hlm003hlm003hlm0_y9ocau.png",
  },
  {
    id: "haircare-04",
    title: "Luxury Hair Ritual",
    description: "Modern editorial-inspired image crafted for premium haircare branding.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106925/Gemini_Generated_Image_q3sanq3sanq3sanq_r1rmyb.png",
  },
  {
    id: "haircare-05",
    title: "Radiant Hair Care",
    description: "Beauty-focused campaign visual celebrating strength, softness, and shine.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781106925/Gemini_Generated_Image_31qhj031qhj031qh_dylcry.png",
  },
  {
    id: "sun-care-01",
    title: "Sunlit Beauty",
    description: "Radiant skincare campaign celebrating healthy, protected skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107058/Gemini_Generated_Image_ar31zhar31zhar31_kzzkka.png",
  },
  {
    id: "sun-care-02",
    title: "Golden Protection",
    description: "Premium beauty visual emphasizing daily UV defense.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107057/Gemini_Generated_Image_29h1gj29h1gj29h1_cde3e9.png",
  },
  {
    id: "sun-care-03",
    title: "Radiance Shield",
    description: "Elegant portrait showcasing confidence and sun protection.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107057/Gemini_Generated_Image_22mzry22mzry22mz_nqp0od.png",
  },
  {
    id: "sun-care-04",
    title: "Daily Defense",
    description: "Modern skincare imagery focused on protection and glow.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107056/Gemini_Generated_Image_8zaag8zaag8zaag8_akz6ez.png",
  },
  {
    id: "sun-care-05",
    title: "Summer Glow",
    description: "Bright beauty campaign designed for premium skincare brands.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107056/Gemini_Generated_Image_7u34k67u34k67u34_c6hwp7.png",
  },
  {
    id: "sun-care-06",
    title: "Protect & Shine",
    description: "Luxury beauty visual highlighting healthy skin confidence.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107055/Gemini_Generated_Image_6i7vxu6i7vxu6i7v_z7tm8m.png",
  },
  {
    id: "sun-care-07",
    title: "Skin First",
    description: "Premium editorial image centered on daily skincare rituals.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107055/Gemini_Generated_Image_5l8y7c5l8y7c5l8y_ezxpes.png",
  },
  {
    id: "sun-care-08",
    title: "Healthy Glow",
    description: "Contemporary beauty photography with a luxury aesthetic.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107055/Gemini_Generated_Image_6ak05c6ak05c6ak0_s5lfix.png",
  },
  {
    id: "sun-care-09",
    title: "Sun Kissed",
    description: "Vibrant skincare portrait showcasing natural radiance.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107054/Gemini_Generated_Image_4u4riu4u4riu4u4r_vzunfv.png",
  },
  {
    id: "sun-care-10",
    title: "Luminous Care",
    description: "Refined beauty campaign designed for modern skincare brands.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107054/Gemini_Generated_Image_4eu60o4eu60o4eu6_rxqsyx.png",
  },
  {
    id: "sun-care-11",
    title: "Bright Horizons",
    description: "Editorial-style visual emphasizing protection and freshness.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107053/Gemini_Generated_Image_2sms0l2sms0l2sms_yrcomx.png",
  },
  {
    id: "sun-care-12",
    title: "Pure Confidence",
    description: "Beauty-focused campaign celebrating healthy skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107053/Gemini_Generated_Image_2ygb7x2ygb7x2ygb_ukepg0.png",
  },
  {
    id: "sun-care-13",
    title: "Sun Defense Pro",
    description: "Premium skincare imagery highlighting SPF protection.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107052/Gemini_Generated_Image_2gmx2o2gmx2o2gmx_y5wv87.png",
  },
  {
    id: "product-spf-01",
    title: "Sun Block SPF 50",
    description: "Hero product showcase designed for premium sunscreen branding.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107052/Sun_block_50_bunwss.png",
  },
  {
    id: "product-spf-03",
    title: "Glorious SPF 50",
    description: "Luxury sunscreen visual crafted for premium skincare campaigns.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107050/Glorious_Sun_block_50_07_t98pm9.png",
  },
  {
    id: "product-spf-04",
    title: "Advanced UV Shield",
    description: "Professional product display showcasing superior protection.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107050/Glorious_Sun_block_50_06_c6gkfh.png",
  },
  {
    id: "product-spf-05",
    title: "Everyday Protection",
    description: "Modern product shot focused on skincare reliability.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107050/Glorious_Sun_block_50_05_fnbgj2.png",
  },
  {
    id: "product-spf-06",
    title: "Shielded Beauty",
    description: "Premium sunscreen presentation with luxury branding appeal.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107049/Glorious_Sun_block_50_04_mu3bsn.png",
  },
  {
    id: "product-spf-07",
    title: "Glow Secure",
    description: "Clean and professional SPF product showcase.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107049/Glorious_Sun_block_50_03_zni4us.png",
  },
  {
    id: "product-spf-08",
    title: "Skin Barrier SPF",
    description: "Elegant sunscreen visual highlighting daily skincare essentials.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107048/Glorious_Sun_block_50_02_aboc3s.png",
  },
  {
    id: "product-spf-10",
    title: "Ultimate UV Care",
    description: "Luxury sunscreen hero shot designed for advertisements.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107047/Glorious_Sun_block_50_cps3vr.png",
  },
  {
    id: "product-spf-11",
    title: "SPF Essentials",
    description: "Professional skincare product image with a clean aesthetic.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107048/Glorious_Sun_block_50_01_can6iw.jpg",
  },
  {
    id: "editorial-spf-01",
    title: "Summer Elegance",
    description: "Luxury editorial beauty shot inspired by premium skincare.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107047/Gemini_Generated_Image_x65w4vx65w4vx65w_l3jtzf.png",
  },
  {
    id: "editorial-spf-02",
    title: "Golden Hour Glow",
    description: "Contemporary beauty visual emphasizing radiant skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107046/Gemini_Generated_Image_wy1cm8wy1cm8wy1c_mjtxcy.png",
  },
  {
    id: "editorial-spf-03",
    title: "Beauty Under Sun",
    description: "Premium portrait crafted for modern skincare storytelling.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107046/Gemini_Generated_Image_vcb1bkvcb1bkvcb1_lpcgt3.png",
  },
  {
    id: "editorial-spf-04",
    title: "Sunlit Confidence",
    description: "Fresh beauty campaign visual showcasing healthy skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107045/Gemini_Generated_Image_tep61step61step6_kxjjg0.png",
  },
  {
    id: "editorial-spf-05",
    title: "Radiant Moments",
    description: "Elegant beauty imagery designed for luxury skincare brands.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107045/Gemini_Generated_Image_ru62omru62omru62_zdfqhf.png",
  },
  {
    id: "editorial-spf-06",
    title: "Natural Shield",
    description: "Creative visual blending beauty, wellness, and protection.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107045/Gemini_Generated_Image_qzia78qzia78qzia_nupfsg.png",
  },
  {
    id: "editorial-spf-07",
    title: "Endless Summer",
    description: "Premium lifestyle-inspired skincare campaign artwork.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107044/Gemini_Generated_Image_q1a6h8q1a6h8q1a6_mh1llw.png",
  },
  {
    id: "editorial-spf-08",
    title: "Glow Beyond",
    description: "Sophisticated beauty portrait with luxury appeal.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107043/Gemini_Generated_Image_pi8xt1pi8xt1pi8x_zi4bum.png",
  },
  {
    id: "editorial-spf-09",
    title: "Skin in Bloom",
    description: "Modern beauty visual celebrating radiant skin health.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107043/Gemini_Generated_Image_mr2q09mr2q09mr2q_wfhpos.png",
  },
  {
    id: "editorial-spf-10",
    title: "Golden Radiance",
    description: "Premium skincare artwork inspired by natural sunlight.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107042/Gemini_Generated_Image_kn5uz0kn5uz0kn5u_iztsp1.png",
  },
  {
    id: "editorial-spf-11",
    title: "Luminous Protection",
    description: "Editorial beauty campaign focused on confidence and care.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107041/Gemini_Generated_Image_jauh6ajauh6ajauh_wkb5jv.png",
  },
  {
    id: "editorial-spf-12",
    title: "Glow Naturally",
    description: "Refined portrait crafted for premium skincare advertising.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107042/Gemini_Generated_Image_jq2qk6jq2qk6jq2q_y10jva.png",
  },
  {
    id: "editorial-spf-13",
    title: "Sun Safe Beauty",
    description: "Luxury skincare visual designed for modern campaigns.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107040/Gemini_Generated_Image_gljb8ngljb8ngljb_gyb6a7.png",
  },
  {
    id: "editorial-spf-14",
    title: "Bright & Protected",
    description: "Creative beauty image celebrating daily skin protection.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107038/Gemini_Generated_Image_c9f00mc9f00mc9f0_ssn2yk.png",
  },
  {
    id: "editorial-spf-15",
    title: "Healthy Glow SPF",
    description: "Premium campaign visual highlighting radiant skin care.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107040/Gemini_Generated_Image_ghr3fvghr3fvghr3_m6jtrr.png",
  },
  {
    id: "editorial-spf-16",
    title: "Beauty in Light",
    description: "Modern editorial artwork blending elegance and protection.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107039/Gemini_Generated_Image_cfqwh8cfqwh8cfqw_vugyfa.png",
  },

   {
    id: "nightcare-01",
    title: "Midnight Repair",
    description: "Luxurious night cream visual focused on overnight skin renewal and deep hydration.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107508/Night_Cream_01_izzdta.png",
  },
  {
    id: "nightcare-02",
    title: "Restorative Glow",
    description: "Premium skincare campaign showcasing radiant skin recovery overnight.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107507/Night_Cream_srqa0c.png",
  },
  {
    id: "nightcare-05",
    title: "Dream Skin Glow",
    description: "Soft editorial beauty visual representing overnight nourishment and glow.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107505/Gemini_Generated_Image_wincaawincaawinc_xb5y7i.png",
  },
  {
    id: "nightcare-06",
    title: "Silk Recovery",
    description: "Elegant skincare campaign image focused on smooth and rejuvenated skin.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107504/Gemini_Generated_Image_tizka8tizka8tizk_rqfj7t.png",
  },
  {
    id: "nightcare-07",
    title: "Deep Nourish",
    description: "Premium beauty visual emphasizing deep skin restoration at night.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107504/Gemini_Generated_Image_rro2d8rro2d8rro2_ppj8bs.png",
  },
  {
    id: "nightcare-08",
    title: "Moonlight Care",
    description: "Luxury skincare imagery inspired by nighttime beauty rituals.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107503/Gemini_Generated_Image_pu9utipu9utipu9u_zqxtjp.png",
  },
  {
    id: "nightcare-09",
    title: "Overnight Radiance",
    description: "Modern editorial beauty shot focused on glow restoration while sleeping.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107502/Gemini_Generated_Image_jbb1j7jbb1j7jbb1_o7qm4j.png",
  },
  {
    id: "nightcare-10",
    title: "Skin Renewal",
    description: "Premium skincare campaign visual showing rejuvenation and hydration.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107502/Gemini_Generated_Image_pfn622pfn622pfn6_isganv.png",
  },
  {
    id: "nightcare-11",
    title: "Night Glow Therapy",
    description: "Luxury beauty visual highlighting deep nourishment and softness.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107502/Gemini_Generated_Image_gkhjzbgkhjzbgkhj_fnqqqv.png",
  },
  {
    id: "nightcare-12",
    title: "Beauty Sleep Formula",
    description: "Elegant skincare artwork designed for premium night cream branding.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107501/Gemini_Generated_Image_dkkca4dkkca4dkkc_she6y5.png",
  },
  {
    id: "nightcare-13",
    title: "Soft Night Recovery",
    description: "Minimal editorial beauty image focusing on calm and skin healing.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107501/Gemini_Generated_Image_cbclq2cbclq2cbcl_aw9nsb.png",
  },
  {
    id: "nightcare-14",
    title: "Velvet Skin Care",
    description: "Premium night skincare campaign emphasizing smooth texture and glow.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107501/Gemini_Generated_Image_atw2aaatw2aaatw2_cbof3p.png",
  },
  {
    id: "nightcare-15",
    title: "Calm Rejuvenation",
    description: "Modern beauty visual representing peaceful overnight skincare routine.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107499/Gemini_Generated_Image_2sdhio2sdhio2sdh_zax7xk.png",
  },
  {
    id: "nightcare-16",
    title: "Glow Restoration",
    description: "Elegant skincare imagery highlighting recovery and radiance.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107499/Gemini_Generated_Image_abfyz9abfyz9abfy_yxojye.png",
  },
  {
    id: "nightcare-17",
    title: "Sleep & Shine",
    description: "Premium beauty campaign visual focused on overnight transformation.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107499/Gemini_Generated_Image_19y2n519y2n519y2_yrcx2p.png",
  },
  {
    id: "nightcare-18",
    title: "Nighttime Renewal",
    description: "Luxury skincare artwork designed for modern beauty branding.",
    src: "https://res.cloudinary.com/dfyqhn5fy/image/upload/v1781107499/Gemini_Generated_Image_1ho0za1ho0za1ho0_vdr0ck.png",
  },
];
